set -g mouse on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind c new-window -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \; display "Config recarregada!"

bind = split-window -h
bind - split-window -v

set -g status-bg black
set -g status-fg white

set -g status-position bottom
set -g status-style bg="#1e1e2e",fg="#cdd6f4"

setw -g window-status-current-style fg="#1e1e2e",bg="#a6e3a1",bold
setw -g window-status-style fg="#cdd6f4",bg="#1e1e2e"

set -g status-left " #[fg=#89b4fa] #S "
set -g status-right "#[fg=#f9e2af]%H:%M #[fg=#94e2d5]%d/%m"

set -g status-justify centre


set -g @bg        "#282a36"
set -g @fg        "#f8f8f2"
set -g @selection "#44475a"

set -g @cyan      "#8be9fd"
set -g @green     "#50fa7b"
set -g @orange    "#ffb86c"
set -g @pink      "#ff79c6"
set -g @purple    "#bd93f9"
set -g @red       "#ff5555"
set -g @yellow    "#f1fa8c"

set -g status-position bottom
set -g status-justify centre
set -g status-style bg="#282a36",fg="#f8f8f2"

set -g status-left-length 100
set -g status-right-length 100

set -g status-interval 1

set -g status-left "#[fg=#8be9fd,bold] 󰣛 #S "

setw -g window-status-format \
"#[fg=#6272a4,bg=#282a36] #I #[fg=#f8f8f2,bg=#282a36]#W "

setw -g window-status-current-format \
"#[fg=#282a36,bg=#50fa7b,bold] #I #[fg=#282a36,bg=#50fa7b,bold]#W "

set -g status-right \
"#[fg=#8be9fd]#(whoami) \
#[fg=#ff79c6]| \
#[fg=#f1fa8c]󰃭 %d/%m \
#[fg=#50fa7b]󰥔 %H:%M "

set -g pane-border-style fg="#44475a"
set -g pane-active-border-style fg="#bd93f9"

set -g message-style bg="#bd93f9",fg="#282a36"

setw -g clock-mode-colour "#50fa7b"

set -g visual-bell off
set -g bell-action none

set -g display-panes-active-colour "#ff79c6"
set -g display-panes-colour "#6272a4"
